### ISSUE TITLE
Models in migrations

### ISSUE THREAD

**Issue by Tensho** [bbatsov/rails-style-guide#143]
Hey, according to ["Don't use model classes in migrations"](https://github.com/bbatsov/rails-style-guide#no-model-class-migrations), what about using models in migrations as just named interface to table in database (without any callbacks, validations, etc.):

``` ruby
Role = Class.new(ActiveRecord::Base)

class ChangeRoleNames < ActiveRecord::Migration
  def change
    reversible do |dir|
      dir.up do
        Role.find_by(name: 'dog').try(:update, name: 'wolfhound')
        Role.find_by(name: 'admin').try(:update, name: 'god')
      end

      dir.down do
        Role.find_by(name: 'wolfhound').try(:update, name: 'dog')
        Role.find_by(name: 'god').try(:update, name: 'admin')
      end
    end
  end
end
```

**Comment by orbanbotond** [comment]
+1

**Comment by ausmith** [comment]
One of the strongest reasons to avoid using models in migrations is that model names can change on you. Today, the model might be named `Role` but tomorrow the model might be named `Theme`. If the migrations were not updated to replace `Role` use with `Theme` use, you now have a migration that's broken, but you locally won't see that problem because you've already run that migration.

**Comment by Tensho** [comment]
Anyway you will use "Find and Replace" or "Refactor - Rename" feature of editor/IDE to change model name for whole project, so this is not a problem. It's really strange, when you rename your model everywhere and forgot to do it in migrations.

**Comment by blairanderson** [comment]
Changing model names is not the biggest problem. It's dependencies that prevent old migrations from working.

That's why migrations stop working, old ones reference AR models and some random dependency throw an error.

A great read about migrations is here:
http://blog.testdouble.com/posts/2014-11-04-healthy-migration-habits.html

I agree with the @tensho. It's totally fine to create a new class for migrations.

**Comment by ausmith** [comment]
I didn't think @Tensho was suggesting creating a new class for migrations. Hard for me to argue in either direction there.

**Comment by Tensho** [comment]
@blairanderson thanks for reference to the article, really nice explanation. According to:
```ruby
class MigrationRole < ActiveRecord::Base
  self.table_name = :roles
end
```
looks nice, but seems to me you need more searches to find such `table_name` assignments in the code while renaming model. So I prefer to stay with just the same model constant and don't introduce another one.

@ausmith  Actually I hope the this code expresses the intention. I diffidently create new class, and what is more important I reassign Role constant with it to overwrite existing preloaded (or autoloader if you like) model with all business logic stuff. And of course I don't blame Rails for using the same load strategy when running migrations as it uses when loading the entire application ^_^

**Comment by ausmith** [comment]
With the additional explanation, your suggestion seems pretty straightforward. While I'm not a huge fan of using it, it logically makes sense and seems like it'd do the trick in a safe manner. My misunderstanding before was I thought the `Role` definition in your sample code was just to set the stage and not directly defined in the migration.

**Comment by Tensho** [comment]
Thanks for the contribution 🙇
