### ISSUE TITLE
Thoughts on the "Flawed gems" section

### ISSUE THREAD

**Issue by deivid-rodriguez** [bbatsov/rails-style-guide#151]
I think we should get rid of it. Instead of negative recommendations, let's add positive ones.

* A negative list is hard to mantain. A positive list too, but it's definitely easier to list the stuff one considers good, than everything one considers bad. For example, if there was a debugging section, one would say here "don't use `ruby-debug`, don't use `debugger` either" where one can just say "use `byebug`".
* A negative list is too subjective. For example, I consider `minitest-autotest` (`autotest` successor) to be as good as `guard`.
* A negative list doesn't have a good vibe. Let's focus on good stuff. Gems like `guard` or `simplecov` only get mentioned in this section, let's encourage their use instead of discouraging the alternatives.

**Comment by katgironpe** [comment]
Agree that it shouldn't be there. For people who like a quick fix (over a real solution), `therubyracer` isn't so bad. Plus, no mention of solutions to specific problems are given. Like "instead of using rubyracer, use multi-build pack on heroku to install node.js." Even if there's no way of knowing where they deploy it, I am certain this problem is only encountered by people who use Paas. 

It may even be best to have a new tool or repo that compares gems if usage (stars, downloads) is confusing. 

Example: 

* https://github.com/ryanb/cancan is now maintained on https://github.com/CanCanCommunity/cancancan (Certain some people do not know that)

**Comment by bbatsov** [comment]
Fine by me.
