### ISSUE TITLE
where().first vs. find_by

### ISSUE THREAD

**Issue by kukula** [bbatsov/rails-style-guide#76]
What do you think, what should I prefer in Rails: `where(field: value).first` or `find_by_field(value)` ?

**Comment by rob-murray** [comment]
So `find_by_field(value)` and `where(field: value)` even with `where(field: value).last` are two different operations resulting in different SQL queries.

`find_by_field(value)` SQL has `LIMIT 1` applied so will be much more efficient than `where(field: value).last` - I would argue that these are not interchangeable and should be used in different circumstances.

If you expect a AR record to exist or not, ie binary decision, yes/no, use `find_by_field` otherwise if you expect many, irrespective of whether you want 1 or more, use `where(field: value)`.

**Comment by bbatsov** [comment]
See https://github.com/bbatsov/rails-style-guide#find_by

**Comment by kukula** [comment]
Great! Thank you @bbatsov !

**Comment by xinspire** [comment]
The following are not equivalent:

```
# bad
User.where(id: id).take

# good
User.find(id)
```

If the id doesn't exist, the first one returns nil, while the second one throws a ActiveRecord::RecordNotFound exception.

**Comment by fffx** [comment]
@xinspire And if id is a out of range value  `User.find(id)` will raise `ActiveRecord::RecordNotfound`, but `User.where(id: id).take` will raise `ActiveModel::RangeError`

see gitlab 500  https://gitlab.com/coldnight/ci-test/issues/464444444444444444444444444444444444
